site_name: {{cookiecutter.project_name}}
theme:
  name: material
  palette:
    primary: white

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
